# version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: audio_hosting_db
    environment:
      POSTGRES_DB: audiohosting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - audio_hosting_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  audio_uploads:

networks:
  audio_hosting_network:
    driver: bridge